#include "generic_tlb.h"
#include "int_tab.h"
#include "dspin_interface.h"
#include "vci_cc_vcache_wrapper.h"
#include "generic_fifo.h"
#include "mapping_table.h"
#include "multi_write_buffer.h"
#include "binary_file_section.h"
#include "vci_initiator.h"
#include "exception.h"
#include "dpp_placeholder.h"
#include "caba_base_module.h"
#include "mips32.h"
#include "binary_file_symbol.h"
#include "gdbserver.h"
#include "iss2.h"
#include "dspin_dhccp_param.h"
#include "generic_cache.h"
#include "segment.h"
#include "vci_param.h"
#include "address_decoding_table.h"
#include "address_masking_table.h"
#include "base_module.h"
#include "loader.h"
#include "/users/cao/peneau/workspace/tsar/modules/vci_cc_vcache_wrapper/caba/source/src/vci_cc_vcache_wrapper.cpp"
#ifndef ENABLE_SCPARSE
template class soclib::caba::VciCcVCacheWrapper<soclib::caba::VciParams<4,8,40,1,1,1,14,4,4,1 > ,39,32,soclib::common::GdbServer<soclib::common::Mips32ElIss >  > ;
#endif
