#include "fb_controller.h"
#include "process_wrapper.h"
#include "vci_buffers.h"
#include "mapping_table.h"
#include "address_masking_table.h"
#include "segment.h"
#include "address_decoding_table.h"
#include "vci_param.h"
#include "exception.h"
#include "linked_access_buffer.h"
#include "dpp_placeholder.h"
#include "caba_base_module.h"
#include "fd_poller.h"
#include "base_module.h"
#include "int_tab.h"
#include "vci_target_fsm.h"
#include "vci_target.h"
#include "vci_framebuffer.h"
#include "/users/cao/peneau/workspace/soclib/soclib/module/connectivity_component/vci_framebuffer/caba/source/src/vci_framebuffer.cpp"
#ifndef ENABLE_SCPARSE
template class soclib::caba::VciFrameBuffer<soclib::caba::VciParams<4,8,40,1,1,1,14,4,4,1 >  > ;
#endif
