#include "vci_buffers.h"
#include "mapping_table.h"
#include "address_masking_table.h"
#include "segment.h"
#include "vci_param.h"
#include "int_tab.h"
#include "address_decoding_table.h"
#include "exception.h"
#include "xicu.h"
#include "dpp_placeholder.h"
#include "caba_base_module.h"
#include "base_module.h"
#include "vci_xicu.h"
#include "vci_target_fsm.h"
#include "vci_target.h"
#include "linked_access_buffer.h"
#include "/users/cao/peneau/workspace/soclib/soclib/module/infrastructure_component/interrupt_infrastructure/vci_xicu/caba/source/src/vci_xicu.cpp"
#ifndef ENABLE_SCPARSE
template class soclib::caba::VciXicu<soclib::caba::VciParams<4,8,40,1,1,1,14,4,4,1 >  > ;
#endif
